:datasett: FKB-Vann
:publisert: 2024-07-01
:versjon: 5.1
:skjemaversjon: 5.1
:versjon-forrige: 5.0.1
:versjon-erstattet-av: 5.1
:underversjon: 2024-07-01
:underversjon-forrige: 2022-01-01
:metadata-url: https://kartkatalog.geonorge.no/metadata/fkb-vann/595e47d9-d201-479c-a77d-cbc1f573a76b
:dokumentstatus: 1
// All informasjon i hode over denne linja må fylles ut for hvert datasett. 
include::../felles_prodspek/filhode.adoc[]

== Innledning, historikk og endringslogg
=== Innledning

FKB-Vann er en del av Felles Kartdatabase (FKB). FKB-spesifikasjonen er en serie produktspesifikasjoner for detaljerte basis geodata som samles inn og forvaltes gjennom Geovekst. Generelle beskrivelser for alle FKB-spesifikasjonene er samlet i FKB-Generell del <<FKB>>.

FKB-Vann beskriver geografisk beliggenhet, forløp og form for bekker, elver, kanaler, grøfter, innsjøer, isbreer og den topografiske delen av kyst og sjø.
Kystkonturen er en del av FKB-Vann og fra og med FKB-Vann versjon 4.6 forvaltes Primærdata Kystkontur som en del av FKB-Vann. 

FKB Generell del finnes {fkbGenerellDel-url}[her].

Mye av detaljinformasjonen om registrering av de ulike objekttypene i FKB er samlet i egne Fotogrammetriske registreringsinstrukser. 
Fotogrammetrisk registreringsinstruks for {datasett} finnes på {reginstr-url}/Fotogrammetrisk_2024-01-01[{reginstr-url}/Fotogrammetrisk_2024-01-01].

Denne produktspesifikasjonen er utarbeidet iht. SOSI produktspesifikasjoner – Krav og godkjenning 5.0 <<SOSI-KRAV>>. UML-modellen som ligger til grunn for innhold i diagrammene og dokumentasjon i kap. 5, følger reglene i SOSI Regler for UML-modellering, versjon 5.1 <<SOSI-UML>>. http://sosi.geonorge.no/veiledere/UML[Denne veilederen] gir hjelp til å lese UML-diagrammene.

=== Historikk
Tidligere versjoner:

* FKB versjon 3.3 oktober 2001 
* FKB versjon 3.4 august 2002 
* FKB-Vann versjon 4.0 – 2007-01-01 
* FKB-Vann versjon 4.01 - 2009-03-10 
* FKB-Vann versjon 4.02 - 2011-12-01 
* FKB-Vann versjon 4.6 – 2016-06-01 
* FKB-Vann versjon 4.6 – 2016-06-01
* FKB-Vann versjon 4.61 – 2018-10-17
* FKB-Vann versjon 5.0 - 2022-01-01
* FKB-Vann versjon 5.0.1 - 2022-01-01


=== Endringslogg

==== Innhold i endringsloggen

FKB 5.0 er en ny hovedversjon av FKB. Dette innebærer at det er gjort større endringer i standarden. Det vil ikke være tilstrekkelig å lese endringsloggen for å få et helhetlig bilde av FKB 5.0 produktspesifikasjonene. For å få et komplett bilde av produktspesifikasjonen må man lese dokumentasjonen som en helhet, inkludert de gjennomgående endringene som er beskrevet i FKB Generell del 5.0 <<FKB>>.

Endringsloggene for det enkelte datasett har som ambisjonsnivå å beskrive de viktigste endringene når det gjelder datainnhold (objekttyper) siden forrige versjon. Endringsloggen vil ikke inneholde alle detaljerte endringer på egenskapsnivå eller endringer når det gjelder utvekslingsformat,  datamodellering eller lignende. 

==== Endringer fra versjon 5.0.1 til versjon 5.1

* Lagt til taggen inlineOrByReference=byReference på alle assosiasjoner
* Justeringer/forbedringer i dokumentasjonsmal. Dokumentasjon kun tilgjengelig på HTML-format. 

==== Endringer fra versjon 5.0 til versjon 5.0.1

* Endret targetNameSpace fra å starte på https til å starte på http
* Endret multiplisitet fra [0..n] til [0..1] på egenskapen eksternpeker på featuretype Innsjø
* Lagt til assosiasjon fra featuretype SnøIsbre til featuretype VannFiktivGrense slik at også SnøIsbre kan avgrenses/deles av fiktive grenser

==== Endringer fra versjon 4.61 til versjon 5.0

* Oppdatert generelle konsepter fra FKB 5.0 generell del. Se <<FKB>> for detaljer.
* Objekttypen _Navigasjonsinstallasjon_ (frittstående fyrlykt) er flyttet til FKB-BygnAnlegg
* Objekttypen _VeggrøftÅpen_ er overført fra FKB-Veg til FKB-Vann
* Objekttypen _ElvBekk_ med geometrirepresentasjon flate er erstattet med ny objekttype _Elv_ (flategeometri).
_ElvBekk_ beskriver nå kun senterlinje (kurvegeometri)
* Objekttypen _KanalGrøft_ med geometrirepresentasjon flate er erstattet med ny objekttype _Kanal_ (flategeometri).
_KanalGrøft_ beskriver nå kun senterlinje (kurvegeometri)
* Objekttypen _ElvBekkKant_ utgår, erstattes av _Elvekant_
* Objekttypen KanalGrøftKant utgår, erstattes av _Kanalkant_
* Ny objekttype _KonnekteringVann_
* Objekttypene _HavElvSperre_, _ElveElvsperre_, _ElvelinjeFiktiv_, _InnsjøElvSperre_, og _InnsjølinjeFiktiv_ utgår og erstattes av ny objekttype _VannFiktivGrense_. Egenskapen _vannSperretype_ med sine kodeverdier definerer ulike typer av fiktive delelinjer
* Objekttypen _InnsjøKantRegulert_ er fjernet, erstattes av objekttypen _Innsjøkant_ med høyde lik høyeste regulerte vannstand, eventuelt fotovannstand hvis den er høyere
* Egenskapen _medium_ er endret fra opsjonell til påkrevd der den benyttes (kodes med ukjent-verdi om nødvendig)
* Egenskapen _kystkonstruksjonstype_ er endret fra opsjonell til påkrevd der den benyttes (kodes med ukjent-verdi om nødvendig)
* Egenskapen _regulert_ (JA/NEI) er innført på objekttype _Innsjø_ for å angi om en innsjø er oppdemt/regulert
* Egenskapen _eksternpeker_ er innført på objekttype Innsjø for å gjøre det mulig å legge inn referanse (i form av URI-er) til tilsvarende objekt forvaltet i andre systemer
* Alle kodelister, dvs. kodeverdiene til egenskapene _kystkonstruksjonstype_, _kystreferanse_, _vannBredde_ og _vannSperretype_, er flyttet ut av produktspesifikasjonen og forvaltes eksternt i https://register.geonorge.no/sosi-kodelister/fkb/vann/5.0[Geonorge].

=== Normative referanser

include::../felles_prodspek/kap14_normativ_ref.adoc[]

<<<

== Definisjoner og forkortelser

=== Definisjoner

include::../felles_prodspek/kap21_definisjoner.adoc[]


=== Forkortelser
include::../felles_prodspek/kap22_forkortelser.adoc[]


== Generelt om spesifikasjonen

=== Unik identifisering
FKBVann

==== Fullstendig navn
FKB-Vann

==== Versjon
{versjon}

=== Referansedato
{underversjon}

=== Ansvarlig organisasjon
Geovekst

=== Språk
nor

=== Hovedtema
Basisdata vann

=== Temakategori
basisData

=== Sammendrag
Spesifikasjonen beskriver geografisk beliggenhet, forløp og form for bekker, elver, kanaler, grøfter, innsjøer, isbreer og den topografiske delen av kyst og sjø.

=== Formål
include::../felles_prodspek/kap38_formal.adoc[]


// Fellesdel som dekker kap 3.9 - 3.12 for alle FKB-produktspesifikasjoner
include::../felles_prodspek/kap39-312_representasjon.adoc[]

<<<

== Spesifikasjonsomfang

include::../felles_prodspek/kap4_omfang.adoc[]  

<<<
 

== Innhold og struktur

=== Omfang
<<HeleDatasettet,Hele datasettet>>

include::modellRapport.adoc[]

<<<

== Referansesystem

include::../felles_prodspek/kap6_referansesystem.adoc[]

<<<

== Kvalitet

include::../felles_prodspek/kap7_kvalitet.adoc[]

<<<

== Datafangst

include::../felles_prodspek/kap8_datafangst.adoc[]

<<<

== Datavedlikehold

include::../felles_prodspek/kap9_vedlikehold.adoc[]

<<<

== Presentasjon

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Referanse til presentasjonskatalog
Presentasjonsregler for FKB-data er angitt i skjermkartografispesifikasjonen: https://register.geonorge.no/register/versjoner/tegneregler/geovekst/fkb-skjermkartografi

<<<

== Leveranse

include::../felles_prodspek/kap11_leveranse.adoc[]

<<<


== Tilleggsinformasjon
Ingen angitt informasjon

<<<

== Metadata

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Metadataspesifikasjon

include::../felles_prodspek/kap13_metadata.adoc[]

<<<

[appendix]
== SOSI-format-realisering

SOSI-realiseringen følger kravene i "Realisering i SOSI-format 5.0" <<SOSI-FORMAT>>. Under en utlisting av SOSI-formatrealiseringen:

include::SOSIformatRealisering.adoc[]


[appendix]
== GML-realisering

GML-realiseringen følger kravene i "Realisering i GML-format 5.0" <<SOSI-GML>>. Realiseringen defineres av følgende filer:

* link:{skjema-url}/FKBVann.xsd[GML-skjema]
* link:{skjema-url}/FKBVann.sch[Schematron-regler til validering av tilleggskrav til datainnhold og -struktur utover det som er definert i GML-skjemafil] (sch-fil)
* link:{skjema-url}/eksempel/[Katalog med eksempelfiler]


:sectnums!:

[descrete]
== Lisensvilkår

// Inkluder lisensvilkår
include::../felles_prodspek/lisensvilkaar.adoc[]
